{% set name = "WeasyPrint" %}
{% set version = "53.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Kozea/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 004c9fcf7c73f2c0a45f63d990eaa660efaf9e47973d572082c8af8e5562f4a6

build:
  number: 0
  noarch: python
  entry_points:
    - weasyprint = weasyprint.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=3.2
    - pip
    - python >=3.6
  run:
    - cffi >=0.6
    - cssselect2 >=0.1
    - fonttools >=4.0.0
    - html5lib >=1.0.1
    - pango >=1.44.0
    - pillow >=4.0.0
    - pydyf >=0.0.3
    - pyphen >=0.9.1
    - python >=3.6
    - tinycss2 >=1.0.0
    - glib  # Temporary, see https://github.com/conda-forge/weasyprint-feedstock/issues/23

test:
  imports:
    - weasyprint
  commands:
    - pip check
    - weasyprint --help
  requires:
    - pip

about:
  home: https://github.com/Kozea/WeasyPrint
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: WeasyPrint converts web documents (HTML with CSS, SVG, …) to PDF

  description: |
    WeasyPrint is a smart solution helping web developers to create PDF
    documents. It turns simple HTML pages into gorgeous statistical
    reports, invoices, tickets…

  doc_url: https://weasyprint.readthedocs.io/en/stable/
  dev_url: https://github.com/Kozea/WeasyPrint

extra:
  recipe-maintainers:
    - mrandrewandrade
    - liZe
