{% set name = "WeasyPrint" %}
{% set version = "60.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/{{ (name|lower)[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}-py3-none-any.whl
  sha256: 55227e5e44f5f34bc9cec651329bd38d063ef7d29151d4b058d4af1ca943d4a7

build:
  number: 1
  skip: True  # [py<37]
  entry_points:
    - weasyprint = weasyprint.__main__:main
  script: {{ PYTHON }} -m pip install {{ name|lower }}-{{ version }}-py3-none-any.whl -vv

requirements:
  host:
    - pip
    - python
  run:
    - cffi >=0.6
    - cssselect2 >=0.1
    - fonttools >=4.0.0
    - html5lib >=1.0.1
    - pango >=1.44.0
    - pillow >=9.1.0
    - pydyf >=0.8.0
    - pyphen >=0.9.1
    - python
    - tinycss2 >=1.0.0
    - glib  # Temporary, see https://github.com/conda-forge/weasyprint-feedstock/issues/23
    - gtk3  # [win]

test:
  imports:
    - weasyprint
  commands:
    - pip check
    - weasyprint --help
  requires:
    - pip

about:
  home: https://github.com/Kozea/WeasyPrint
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ name|lower }}-{{ version }}.dist-info/LICENSE
  summary: WeasyPrint converts web documents (HTML with CSS, SVG, …) to PDF

  description: |
    WeasyPrint is a smart solution helping web developers to create PDF
    documents. It turns simple HTML pages into gorgeous statistical
    reports, invoices, tickets…

  doc_url: https://doc.courtbouillon.org/weasyprint/stable/
  dev_url: https://github.com/Kozea/WeasyPrint

extra:
  recipe-maintainers:
    - mrandrewandrade
    - liZe
