{% set name = "WeasyPrint" %}
{% set version = "64.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/{{ (name|lower)[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}-py3-none-any.whl
  sha256: f7c88ea8ce0ce0c527cbb9c802689e035fae50016d7efc5dfdaba4b75abf68f4

build:
  number: 0
  noarch: python
  entry_points:
    - weasyprint = weasyprint.__main__:main
  script: {{ PYTHON }} -m pip install {{ name|lower }}-{{ version }}-py3-none-any.whl -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cffi >=0.6
    - cssselect2 >=0.1
    - fonttools >=4.0.0
    - html5lib >=1.1
    - pango >=1.44.0
    - pillow >=9.1.0
    - pydyf >=0.10.0
    - pyphen >=0.9.1
    - python >={{ python_min }}
    - tinycss2 >=1.3.0
    - glib  # Temporary, see https://github.com/conda-forge/weasyprint-feedstock/issues/23

test:
  imports:
    - weasyprint
  commands:
    - pip check
    - weasyprint --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kozea/WeasyPrint
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ name|lower }}-{{ version }}.dist-info/LICENSE
  summary: WeasyPrint converts web documents (HTML with CSS, SVG, …) to PDF

  description: |
    WeasyPrint is a smart solution helping web developers to create PDF
    documents. It turns simple HTML pages into gorgeous statistical
    reports, invoices, tickets…

  doc_url: https://doc.courtbouillon.org/weasyprint/stable/
  dev_url: https://github.com/Kozea/WeasyPrint

extra:
  recipe-maintainers:
    - mrandrewandrade
    - liZe
