{% set name = "WeasyPrint" %}
{% set version = "52.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Kozea/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 69816d5fa1d861c4edb5dcb364e44282410b046a758e0f872447c2712f06cc72

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pango
    - setuptools >=39.2.0
    - cffi >=0.6
    - html5lib >=0.999999999
    - cairocffi >=0.9.0
    - tinycss2 >=1.0.0
    - cssselect2 >=0.1
    - cairosvg >=2.4.0
    - pyphen >=0.8
    - pillow >=4.0.0
    - pytest-runner
    - xorg-libxrender
    - xorg-libxext

  run:
    - python
    - pango
    - setuptools >=39.2.0
    - cffi >=0.6
    - html5lib >=0.999999999
    - cairocffi >=0.9.0
    - tinycss2 >=1.0.0
    - cssselect2 >=0.1
    - cairosvg >=2.4.0
    - pyphen >=0.8
    - pillow >=4.0.0
    - xorg-libxrender
    - xorg-libxext

test:
  imports:
    - weasyprint

about:
  home: https://github.com/Kozea/WeasyPrint
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: WeasyPrint converts web documents (HTML with CSS, SVG, …) to PDF

  description: |
    WeasyPrint is a smart solution helping web developers to create PDF
    documents. It turns simple HTML pages into gorgeous statistical
    reports, invoices, tickets…

  doc_url: https://weasyprint.readthedocs.io/en/stable/
  dev_url: https://github.com/Kozea/WeasyPrint

extra:
  recipe-maintainers:
    - mrandrewandrade
    - liZe
